### PR TITLE
added logging statements

### PR DESCRIPTION
**Pull request by KJStick**

### CODE REVIEW

**Comment by ppajersk** [comment]
Can you rebase with main so the workflow gets the updated python ver matrix for linting?

**Review by ppajersk — APPROVED** [review]
Looks good to me

**Comment by ppajersk** [comment]
Needed to add the verify=false flag as well as fixing the api global var to be the correct name

**Review by jlothian — APPROVED** [review]
Looks good, mostly really just fixing the pylint stuff 👍

**Pull request merged**
